import { Product } from "@/types";

export const products: Product[] = [
    {
        id: "1",
        name: "Wireless Bluetooth Headphones",
        description: "High-quality over-ear Bluetooth headphones",
        longDescription: "Experience immersive sound with these wireless headphones featuring noise cancellation and 30-hour battery life.",
        price: 89.99,
        originalPrice: 129.99,
        productImages: ["/images/headphones1.jpg"],
        stock: 45,
        rating: 4.5,
        reviewCount: 120,
        features: ["Noise Cancellation", "Bluetooth 5.0", "30-hour Battery", "Foldable"],
        weight: "0.5kg",
        dimensions: "20x18x8 cm",
        modelNumber: "WH-BT500",
        warranty: "1 year",
        countryOfOrigin: "China",
        onSale: true,
        isActive: true,
        isFeatured: true,
        category: { name: "Electronics", slug: "electronics" },
        },
        {
        id: "2",
        name: "Smartwatch Series 6",
        description: "Next-gen smartwatch with fitness tracking",
        longDescription: "Track your workouts, heart rate, and sleep with the latest Smartwatch Series 6.",
        price: 199.99,
        originalPrice: 249.99,
      productImages: ["/images/smartwatch.jpg"],
      stock: 30,
      rating: 4.2,
      reviewCount: 85,
      features: ["Heart Rate Monitor", "GPS", "Sleep Tracking"],
      weight: "0.15kg",
      dimensions: "4x4x1 cm",
      modelNumber: "SW-6X",
      warranty: "2 years",
      countryOfOrigin: "USA",
      onSale: true,
      isActive: true,
      isFeatured: false,
      category: { name: "Wearables", slug: "wearables" },
    },
    {
      id: "3",
      name: "Ergonomic Office Chair",
      description: "Comfortable mesh office chair",
      longDescription: "Built for long working hours with adjustable height, lumbar support, and breathable mesh back.",
      price: 149.99,
      productImages: ["/images/chair.jpg"],
      stock: 20,
      rating: 4.7,
      reviewCount: 67,
      features: ["Adjustable Height", "Lumbar Support", "360° Swivel"],
      weight: "12kg",
      dimensions: "70x70x120 cm",
      modelNumber: "OC-MESH900",
      warranty: "1 year",
      countryOfOrigin: "India",
      isActive: true,
      isFeatured: true,
      category: { name: "Furniture", slug: "furniture" },
    },
    {
      id: "4",
      name: "Gaming Mouse Pro X",
      description: "RGB gaming mouse with 12000 DPI",
      price: 59.99,
      productImages: ["/images/mouse.jpg"],
      stock: 100,
      rating: 4.3,
      reviewCount: 240,
      features: ["12000 DPI", "RGB Lighting", "6 Programmable Buttons"],
      weight: "0.2kg",
      dimensions: "13x7x4 cm",
      modelNumber: "GMX-12K",
      warranty: "6 months",
      countryOfOrigin: "Germany",
      onSale: false,
      isActive: true,
      category: { name: "Gaming", slug: "gaming" },
    },
    {
      id: "5",
      name: "4K UHD Smart TV 55\"",
      description: "Crystal-clear display with built-in apps",
      longDescription: "Enjoy stunning visuals with this 4K Ultra HD Smart TV. Supports Netflix, YouTube, and more.",
      price: 499.99,
      originalPrice: 599.99,
      productImages: ["/images/tv.jpg"],
      stock: 15,
      rating: 4.6,
      reviewCount: 310,
      features: ["4K UHD", "Smart Apps", "55-inch Display"],
      weight: "15kg",
      dimensions: "123x71x8 cm",
      modelNumber: "TV-4K55S",
      warranty: "2 years",
      countryOfOrigin: "South Korea",
      onSale: true,
      isActive: true,
      isFeatured: true,
      category: { name: "Home Entertainment", slug: "home-entertainment" },
    },
    {
      id: "6",
      name: "Electric Kettle 1.5L",
      description: "Fast boiling electric kettle",
      price: 29.99,
      productImages: ["/images/kettle.jpg"],
      stock: 60,
      rating: 4.1,
      reviewCount: 40,
      features: ["1.5L Capacity", "Auto Shut-Off", "Stainless Steel Body"],
      weight: "1kg",
      dimensions: "20x15x25 cm",
      modelNumber: "EK-15SS",
      warranty: "1 year",
      countryOfOrigin: "India",
      onSale: false,
      isActive: true,
      category: { name: "Appliances", slug: "appliances" },
    },
    {
      id: "7",
      name: "Mechanical Keyboard RGB",
      description: "Tactile feedback keyboard with RGB lights",
      price: 79.99,
      productImages: ["/images/keyboard.jpg"],
      stock: 50,
      rating: 4.4,
      reviewCount: 95,
      features: ["Mechanical Keys", "RGB Backlight", "Anti-Ghosting"],
      weight: "1.2kg",
      dimensions: "44x14x3.5 cm",
      modelNumber: "MK-RGB200",
      warranty: "1 year",
      countryOfOrigin: "China",
      onSale: false,
      isActive: true,
      category: { name: "Peripherals", slug: "herbal-tea" },
    },
    {
      id: "8",
      name: "Smartphone 128GB",
      description: "Fast, sleek smartphone with great camera",
      price: 699.99,
      originalPrice: 749.99,
      productImages: ["/images/phone.jpg"],
      stock: 25,
      rating: 4.8,
      reviewCount: 520,
      features: ["128GB Storage", "Triple Camera", "5G Support"],
      weight: "0.18kg",
      dimensions: "15x7.5x0.8 cm",
      modelNumber: "SP-128X5G",
      warranty: "2 years",
      countryOfOrigin: "Vietnam",
      onSale: true,
      isActive: true,
      isFeatured: true,
      category: { name: "Mobile Phones", slug: "herbal-tea" },
    },
    {
      id: "9",
      name: "Stainless Steel Cookware Set",
      description: "10-piece kitchen cookware set",
      price: 149.99,
      productImages: ["/images/cookware.jpg"],
      stock: 35,
      rating: 4.0,
      reviewCount: 60,
      features: ["Stainless Steel", "Dishwasher Safe", "Induction Friendly"],
      weight: "6kg",
      dimensions: "60x40x30 cm",
      modelNumber: "CW-10SS",
      warranty: "3 years",
      countryOfOrigin: "India",
      isActive: true,
      isFeatured: false,
      category: { name: "Kitchen", slug: "kitchen" },
    },
    {
      id: "10",
      name: "Noise Cancelling Earbuds",
      description: "Compact wireless earbuds with ANC",
      price: 129.99,
      originalPrice: 159.99,
      productImages: ["/images/earbuds.jpg"],
      stock: 70,
      rating: 4.6,
      reviewCount: 310,
      features: ["ANC", "Wireless Charging", "Touch Controls"],
      weight: "0.05kg",
      dimensions: "2x2x3 cm",
      modelNumber: "NB-ANC300",
      warranty: "1 year",
      countryOfOrigin: "China",
      onSale: true,
      isActive: true,
      isFeatured: false,
      category: { name: "Audio", slug: "audio" },
    },
  ];
